issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: 'SA1019: schema.SchemaValidateFunc is deprecated'
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - nilerr
    # - paralleltest # Reference: https://github.com/kunwardeep/paralleltest/issues/14
    - predeclared
    - staticcheck
    - usetesting
    - unconvert
    - unparam
    - unused
    - govet

run:
  # Prevent false positive timeouts in CI
  timeout: 5m