# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: Provider-related Feedback and Questions
    url: https://github.com/terraform-providers
    about: Each provider (e.g. AWS, Azure, GCP, Oracle, K8S, etc.) has its own repository, any provider related issues or questions should be directed to appropriate provider repository.
  - name: Terraform Language or Workflow Feedback and Questions
    url: https://github.com/hashicorp/terraform/issues/new/choose
    about: Terraform Core has its own repository, any language (HCL) or workflow related issues or questions should be directed there.
  - name: ❓ Plugin SDK Questions
    url: https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk
    about: Please ask and answer SDK related questions through the Plugin SDK Community Forum.
